# Generated by Django 4.2.4 on 2023-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
