# Generated by Django 4.2.4 on 2023-11-08 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 9), primary_key=True, serialize=False),
        ),
    ]
