# Generated by Django 4.2.4 on 2023-11-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_product_id_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
        ),
    ]
